Resources:
  UnencryptedBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "test-unencrypted-bucket"

  OpenSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow all inbound traffic"
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: "10.0.0.0/0"
